# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Versa3dMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Versa3dMainWindow(object):
    def setupUi(self, Versa3dMainWindow):
        Versa3dMainWindow.setObjectName("Versa3dMainWindow")
        Versa3dMainWindow.resize(1004, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Versa3dMainWindow.sizePolicy().hasHeightForWidth())
        Versa3dMainWindow.setSizePolicy(sizePolicy)
        Versa3dMainWindow.setMinimumSize(QtCore.QSize(1004, 600))
        self.centralWidget = QtWidgets.QWidget(Versa3dMainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.main_horizontal_layout = QtWidgets.QHBoxLayout()
        self.main_horizontal_layout.setContentsMargins(11, 11, 11, 11)
        self.main_horizontal_layout.setSpacing(6)
        self.main_horizontal_layout.setObjectName("main_horizontal_layout")
        self.vtkWidget = QVTKRenderWindowInteractor(self.centralWidget)
        self.vtkWidget.setMinimumSize(QtCore.QSize(600, 500))
        self.vtkWidget.setObjectName("vtkWidget")
        self.main_horizontal_layout.addWidget(self.vtkWidget)
        self.right_side_vertical_layout = QtWidgets.QVBoxLayout()
        self.right_side_vertical_layout.setContentsMargins(11, 11, 11, 11)
        self.right_side_vertical_layout.setSpacing(6)
        self.right_side_vertical_layout.setObjectName("right_side_vertical_layout")
        self.GenerateMachineCodeButton = QtWidgets.QPushButton(self.centralWidget)
        self.GenerateMachineCodeButton.setObjectName("GenerateMachineCodeButton")
        self.right_side_vertical_layout.addWidget(self.GenerateMachineCodeButton)
        self.SliceButton = QtWidgets.QPushButton(self.centralWidget)
        self.SliceButton.setObjectName("SliceButton")
        self.right_side_vertical_layout.addWidget(self.SliceButton)
        self.splitter_right_side = QtWidgets.QSplitter(self.centralWidget)
        self.splitter_right_side.setOrientation(QtCore.Qt.Vertical)
        self.splitter_right_side.setObjectName("splitter_right_side")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_right_side)
        self.layoutWidget.setObjectName("layoutWidget")
        self.layout_split_right_tab = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.layout_split_right_tab.setContentsMargins(11, 11, 11, 11)
        self.layout_split_right_tab.setSpacing(6)
        self.layout_split_right_tab.setObjectName("layout_split_right_tab")
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(325, 100))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.slice_tab = QtWidgets.QWidget()
        self.slice_tab.setObjectName("slice_tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.slice_tab)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.slice_viewer = QVTKRenderWindowInteractor(self.slice_tab)
        self.slice_viewer.setMinimumSize(QtCore.QSize(310, 0))
        self.slice_viewer.setAutoFillBackground(False)
        self.slice_viewer.setObjectName("slice_viewer")
        self.horizontalLayout_4.addWidget(self.slice_viewer)
        self.tabWidget.addTab(self.slice_tab, "")
        self.infill_tab = QtWidgets.QWidget()
        self.infill_tab.setObjectName("infill_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.infill_tab)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.inFilltype_label = QtWidgets.QLabel(self.infill_tab)
        self.inFilltype_label.setObjectName("inFilltype_label")
        self.verticalLayout.addWidget(self.inFilltype_label)
        self.comboBox = QtWidgets.QComboBox(self.infill_tab)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.tabWidget.addTab(self.infill_tab, "")
        self.raster_tab = QtWidgets.QWidget()
        self.raster_tab.setObjectName("raster_tab")
        self.tabWidget.addTab(self.raster_tab, "")
        self.layout_split_right_tab.addWidget(self.tabWidget)
        self.layout_scroll_bar = QtWidgets.QVBoxLayout()
        self.layout_scroll_bar.setContentsMargins(11, 11, 11, 11)
        self.layout_scroll_bar.setSpacing(6)
        self.layout_scroll_bar.setObjectName("layout_scroll_bar")
        self.layout_layerNumberWidget = QtWidgets.QVBoxLayout()
        self.layout_layerNumberWidget.setContentsMargins(11, 11, 11, 11)
        self.layout_layerNumberWidget.setSpacing(6)
        self.layout_layerNumberWidget.setObjectName("layout_layerNumberWidget")
        self.layerNum_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.layerNum_label.setFont(font)
        self.layerNum_label.setObjectName("layerNum_label")
        self.layout_layerNumberWidget.addWidget(self.layerNum_label)
        self.LayerNumberLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LayerNumberLineEdit.setFont(font)
        self.LayerNumberLineEdit.setText("")
        self.LayerNumberLineEdit.setObjectName("LayerNumberLineEdit")
        self.layout_layerNumberWidget.addWidget(self.LayerNumberLineEdit)
        self.layout_scroll_bar.addLayout(self.layout_layerNumberWidget)
        self.verticalSlider = QtWidgets.QSlider(self.layoutWidget)
        self.verticalSlider.setMouseTracking(True)
        self.verticalSlider.setToolTipDuration(1)
        self.verticalSlider.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.verticalSlider.setMinimum(1)
        self.verticalSlider.setMaximum(100)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setInvertedAppearance(False)
        self.verticalSlider.setInvertedControls(False)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.verticalSlider.setObjectName("verticalSlider")
        self.layout_scroll_bar.addWidget(self.verticalSlider)
        self.layout_split_right_tab.addLayout(self.layout_scroll_bar)
        self.optionTabs = QtWidgets.QTabWidget(self.splitter_right_side)
        self.optionTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.optionTabs.setObjectName("optionTabs")
        self.machine_tab = QtWidgets.QWidget()
        self.machine_tab.setObjectName("machine_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.machine_tab)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.systemImage = QtWidgets.QLabel(self.machine_tab)
        self.systemImage.setText("")
        self.systemImage.setObjectName("systemImage")
        self.horizontalLayout.addWidget(self.systemImage)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.machineLabel = QtWidgets.QLabel(self.machine_tab)
        self.machineLabel.setObjectName("machineLabel")
        self.verticalLayout_4.addWidget(self.machineLabel)
        self.processLabel = QtWidgets.QLabel(self.machine_tab)
        self.processLabel.setObjectName("processLabel")
        self.verticalLayout_4.addWidget(self.processLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.optionTabs.addTab(self.machine_tab, "")
        self.machines_settingstab = QtWidgets.QWidget()
        self.machines_settingstab.setObjectName("machines_settingstab")
        self.optionTabs.addTab(self.machines_settingstab, "")
        self.output_tab = QtWidgets.QWidget()
        self.output_tab.setObjectName("output_tab")
        self.optionTabs.addTab(self.output_tab, "")
        self.scripting_tab = QtWidgets.QWidget()
        self.scripting_tab.setObjectName("scripting_tab")
        self.optionTabs.addTab(self.scripting_tab, "")
        self.right_side_vertical_layout.addWidget(self.splitter_right_side)
        self.main_horizontal_layout.addLayout(self.right_side_vertical_layout)
        self.horizontalLayout_3.addLayout(self.main_horizontal_layout)
        Versa3dMainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Versa3dMainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1004, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        Versa3dMainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Versa3dMainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        Versa3dMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Versa3dMainWindow)
        self.statusBar.setObjectName("statusBar")
        Versa3dMainWindow.setStatusBar(self.statusBar)
        self.actionImport_STL = QtWidgets.QAction(Versa3dMainWindow)
        self.actionImport_STL.setObjectName("actionImport_STL")
        self.menuFile.addAction(self.actionImport_STL)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Versa3dMainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.optionTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Versa3dMainWindow)
        Versa3dMainWindow.setTabOrder(self.optionTabs, self.GenerateMachineCodeButton)
        Versa3dMainWindow.setTabOrder(self.GenerateMachineCodeButton, self.tabWidget)

    def retranslateUi(self, Versa3dMainWindow):
        _translate = QtCore.QCoreApplication.translate
        Versa3dMainWindow.setWindowTitle(_translate("Versa3dMainWindow", "MainWindow"))
        self.GenerateMachineCodeButton.setText(_translate("Versa3dMainWindow", "Generate Machine Code"))
        self.SliceButton.setText(_translate("Versa3dMainWindow", "Slice"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.slice_tab), _translate("Versa3dMainWindow", "Slice"))
        self.inFilltype_label.setText(_translate("Versa3dMainWindow", "infill type"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.infill_tab), _translate("Versa3dMainWindow", "Infill"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.raster_tab), _translate("Versa3dMainWindow", "Raster"))
        self.layerNum_label.setText(_translate("Versa3dMainWindow", "Layer #"))
        self.machineLabel.setText(_translate("Versa3dMainWindow", "Machine: MSAM Research Platform"))
        self.processLabel.setText(_translate("Versa3dMainWindow", "Process: Hybrid Silicone AM "))
        self.optionTabs.setTabText(self.optionTabs.indexOf(self.machine_tab), _translate("Versa3dMainWindow", "Machine"))
        self.optionTabs.setTabText(self.optionTabs.indexOf(self.machines_settingstab), _translate("Versa3dMainWindow", "Machine Settings"))
        self.optionTabs.setTabText(self.optionTabs.indexOf(self.output_tab), _translate("Versa3dMainWindow", "Output"))
        self.optionTabs.setTabText(self.optionTabs.indexOf(self.scripting_tab), _translate("Versa3dMainWindow", "Scripting"))
        self.menuFile.setTitle(_translate("Versa3dMainWindow", "File"))
        self.actionImport_STL.setText(_translate("Versa3dMainWindow", "Import stl"))

from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
