# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './designer_files/Versa3dMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Versa3dMainWindow(object):
    def setupUi(self, Versa3dMainWindow):
        Versa3dMainWindow.setObjectName("Versa3dMainWindow")
        Versa3dMainWindow.resize(1004, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Versa3dMainWindow.sizePolicy().hasHeightForWidth())
        Versa3dMainWindow.setSizePolicy(sizePolicy)
        Versa3dMainWindow.setMinimumSize(QtCore.QSize(1004, 600))
        self.centralWidget = QtWidgets.QWidget(Versa3dMainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.MainViewTab = QtWidgets.QTabWidget(self.centralWidget)
        self.MainViewTab.setObjectName("MainViewTab")
        self.Plater = QtWidgets.QWidget()
        self.Plater.setObjectName("Plater")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Plater)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ViewerTab = QtWidgets.QTabWidget(self.Plater)
        self.ViewerTab.setTabPosition(QtWidgets.QTabWidget.South)
        self.ViewerTab.setObjectName("ViewerTab")
        self.Model_ViewerTab = QtWidgets.QWidget()
        self.Model_ViewerTab.setObjectName("Model_ViewerTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Model_ViewerTab)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vtkWidget = QVTKRenderWindowInteractor(self.Model_ViewerTab)
        self.vtkWidget.setMinimumSize(QtCore.QSize(600, 500))
        self.vtkWidget.setObjectName("vtkWidget")
        self.horizontalLayout_2.addWidget(self.vtkWidget)
        self.ViewerTab.addTab(self.Model_ViewerTab, "")
        self.Slice_ViewerTab = QtWidgets.QWidget()
        self.Slice_ViewerTab.setObjectName("Slice_ViewerTab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Slice_ViewerTab)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Image_SliceViewer = QVTKRenderWindowInteractor(self.Slice_ViewerTab)
        self.Image_SliceViewer.setObjectName("Image_SliceViewer")
        self.horizontalLayout_6.addWidget(self.Image_SliceViewer)
        self.sliderGroup = QtWidgets.QVBoxLayout()
        self.sliderGroup.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.sliderGroup.setContentsMargins(11, 11, 11, 11)
        self.sliderGroup.setSpacing(6)
        self.sliderGroup.setObjectName("sliderGroup")
        self.NumLayerLabel = QtWidgets.QLabel(self.Slice_ViewerTab)
        self.NumLayerLabel.setMinimumSize(QtCore.QSize(40, 20))
        self.NumLayerLabel.setMaximumSize(QtCore.QSize(60, 16777215))
        self.NumLayerLabel.setObjectName("NumLayerLabel")
        self.sliderGroup.addWidget(self.NumLayerLabel)
        self.NumLayerSpinBox = QtWidgets.QSpinBox(self.Slice_ViewerTab)
        self.NumLayerSpinBox.setMinimumSize(QtCore.QSize(40, 20))
        self.NumLayerSpinBox.setMaximumSize(QtCore.QSize(60, 16777215))
        self.NumLayerSpinBox.setObjectName("NumLayerSpinBox")
        self.sliderGroup.addWidget(self.NumLayerSpinBox)
        self.NumLayerSlider = QtWidgets.QSlider(self.Slice_ViewerTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NumLayerSlider.sizePolicy().hasHeightForWidth())
        self.NumLayerSlider.setSizePolicy(sizePolicy)
        self.NumLayerSlider.setMinimumSize(QtCore.QSize(0, 0))
        self.NumLayerSlider.setMaximumSize(QtCore.QSize(60, 16777215))
        self.NumLayerSlider.setOrientation(QtCore.Qt.Vertical)
        self.NumLayerSlider.setObjectName("NumLayerSlider")
        self.sliderGroup.addWidget(self.NumLayerSlider)
        self.horizontalLayout_6.addLayout(self.sliderGroup)
        self.ViewerTab.addTab(self.Slice_ViewerTab, "")
        self.horizontalLayout.addWidget(self.ViewerTab)
        self.right_side_vertical_layout = QtWidgets.QVBoxLayout()
        self.right_side_vertical_layout.setContentsMargins(11, 11, 11, 11)
        self.right_side_vertical_layout.setSpacing(6)
        self.right_side_vertical_layout.setObjectName("right_side_vertical_layout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.PrintSettingLabel = QtWidgets.QLabel(self.Plater)
        self.PrintSettingLabel.setObjectName("PrintSettingLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.PrintSettingLabel)
        self.PrintSettingComboBox = QtWidgets.QComboBox(self.Plater)
        self.PrintSettingComboBox.setObjectName("PrintSettingComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.PrintSettingComboBox)
        self.PrintHeadLabel = QtWidgets.QLabel(self.Plater)
        self.PrintHeadLabel.setObjectName("PrintHeadLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.PrintHeadLabel)
        self.PrintHeadComboBox = QtWidgets.QComboBox(self.Plater)
        self.PrintHeadComboBox.setObjectName("PrintHeadComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.PrintHeadComboBox)
        self.PrinterLabel = QtWidgets.QLabel(self.Plater)
        self.PrinterLabel.setObjectName("PrinterLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.PrinterLabel)
        self.PrinterComboBox = QtWidgets.QComboBox(self.Plater)
        self.PrinterComboBox.setObjectName("PrinterComboBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.PrinterComboBox)
        self.ExportGCodeButton = QtWidgets.QPushButton(self.Plater)
        self.ExportGCodeButton.setObjectName("ExportGCodeButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ExportGCodeButton)
        self.right_side_vertical_layout.addLayout(self.formLayout)
        self.TableSTL = QtWidgets.QTableWidget(self.Plater)
        self.TableSTL.setColumnCount(3)
        self.TableSTL.setObjectName("TableSTL")
        self.TableSTL.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableSTL.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableSTL.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableSTL.setHorizontalHeaderItem(2, item)
        self.right_side_vertical_layout.addWidget(self.TableSTL)
        self.horizontalLayout.addLayout(self.right_side_vertical_layout)
        self.MainViewTab.addTab(self.Plater, "")
        self.horizontalLayout_3.addWidget(self.MainViewTab)
        Versa3dMainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Versa3dMainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1004, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        Versa3dMainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Versa3dMainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        Versa3dMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Versa3dMainWindow)
        self.statusBar.setObjectName("statusBar")
        Versa3dMainWindow.setStatusBar(self.statusBar)
        self.actionImport_STL = QtWidgets.QAction(Versa3dMainWindow)
        self.actionImport_STL.setObjectName("actionImport_STL")
        self.actionUndo = QtWidgets.QAction(Versa3dMainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(Versa3dMainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actioncopy = QtWidgets.QAction(Versa3dMainWindow)
        self.actioncopy.setObjectName("actioncopy")
        self.actionpaste = QtWidgets.QAction(Versa3dMainWindow)
        self.actionpaste.setObjectName("actionpaste")
        self.actiondelete = QtWidgets.QAction(Versa3dMainWindow)
        self.actiondelete.setObjectName("actiondelete")
        self.actionSelection_Mode = QtWidgets.QAction(Versa3dMainWindow)
        self.actionSelection_Mode.setObjectName("actionSelection_Mode")
        self.actionCamera_Mode = QtWidgets.QAction(Versa3dMainWindow)
        self.actionCamera_Mode.setObjectName("actionCamera_Mode")
        self.menuFile.addAction(self.actionImport_STL)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actioncopy)
        self.menuEdit.addAction(self.actionpaste)
        self.menuEdit.addAction(self.actiondelete)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.mainToolBar.addAction(self.actionSelection_Mode)
        self.mainToolBar.addAction(self.actionCamera_Mode)

        self.retranslateUi(Versa3dMainWindow)
        self.MainViewTab.setCurrentIndex(0)
        self.ViewerTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Versa3dMainWindow)

    def retranslateUi(self, Versa3dMainWindow):
        _translate = QtCore.QCoreApplication.translate
        Versa3dMainWindow.setWindowTitle(_translate("Versa3dMainWindow", "MainWindow"))
        self.ViewerTab.setTabText(self.ViewerTab.indexOf(self.Model_ViewerTab), _translate("Versa3dMainWindow", "Model Viewer"))
        self.NumLayerLabel.setText(_translate("Versa3dMainWindow", "Layer #"))
        self.ViewerTab.setTabText(self.ViewerTab.indexOf(self.Slice_ViewerTab), _translate("Versa3dMainWindow", "Slice Viewer"))
        self.PrintSettingLabel.setText(_translate("Versa3dMainWindow", "Print settings: "))
        self.PrintHeadLabel.setText(_translate("Versa3dMainWindow", "Print Head:"))
        self.PrinterLabel.setText(_translate("Versa3dMainWindow", "Printer:"))
        self.ExportGCodeButton.setText(_translate("Versa3dMainWindow", "Export G-Code"))
        item = self.TableSTL.horizontalHeaderItem(0)
        item.setText(_translate("Versa3dMainWindow", "Name"))
        item = self.TableSTL.horizontalHeaderItem(1)
        item.setText(_translate("Versa3dMainWindow", "Copies"))
        item = self.TableSTL.horizontalHeaderItem(2)
        item.setText(_translate("Versa3dMainWindow", "Scale"))
        self.MainViewTab.setTabText(self.MainViewTab.indexOf(self.Plater), _translate("Versa3dMainWindow", "Plater"))
        self.menuFile.setTitle(_translate("Versa3dMainWindow", "File"))
        self.menuEdit.setTitle(_translate("Versa3dMainWindow", "Edit"))
        self.menuView.setTitle(_translate("Versa3dMainWindow", "View"))
        self.actionImport_STL.setText(_translate("Versa3dMainWindow", "Import stl"))
        self.actionUndo.setText(_translate("Versa3dMainWindow", "Undo"))
        self.actionRedo.setText(_translate("Versa3dMainWindow", "Redo"))
        self.actioncopy.setText(_translate("Versa3dMainWindow", "cut"))
        self.actionpaste.setText(_translate("Versa3dMainWindow", "copy"))
        self.actiondelete.setText(_translate("Versa3dMainWindow", "paste"))
        self.actionSelection_Mode.setText(_translate("Versa3dMainWindow", "Selection Mode"))
        self.actionCamera_Mode.setText(_translate("Versa3dMainWindow", "Camera Mode"))

from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
from . import res_rc
