[build-system]
requires = [
    "setuptools>=42",
    "ninja",
    "wheel",
    "cmake>=3.12",
    "scikit-build",
    "pybind11",
    "pyinstaller"
]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
    'attrs',
    'vtk',
    'pyqt',
    'numpy',
    'pillow',
    'nomkl',
]
